project:
  type: website
  output-dir: docs

website:
  title: "Lauryn Howlett"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume/index2.qmd
        text: Resume
      - href: about.qmd
        text: My Projects

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

